### ISSUE TITLE
Button is not showing on ojs

### ISSUE THREAD

**Issue by waqas1223** [Vitaliy-1/docxConverter#11]
Hi Vitaliy

Thanks for publishing this. We run a small journal and need to convert all our published articles into XML for PubMed.
i am trying to to install plugin many time time through cPanel but failed .
can you make small video for tutorial i am searching a lot on on google and YouTube.

**Comment by Vitaliy-1** [comment]
What OJS and plugin version are you using?
Are there any associated errors in PHP logs?

**Comment by waqas1223** [comment]
Open Journal Systems 3.2.1.0 version we are used. actually we can not  find any php error.first we remove DOCconverts- master from Cpannle then we install DOCtoJat plugin then when we go ojs administration >setting> plugging then we all plugging doesn't show. then we reinstall old docconverts-master plugin then its show all plugin.
its really appreciated that if sir resolve this issue .  our jurnal site
http://archivessr.com/index.php/asr/index

**Comment by waqas1223** [comment]
We are currently using Open Journal Systems 3.2.1.0 version with our journal www.archivessr.com. We are not facing any PHP error. We have installed DOCX2JAT plugin instead of the previous plugin DOCconverts master from C panel but after installation when we try to enable the DOCS2JATS plugin from OJS administration, the plugins do not show in the list of the plugins to be activated and loading bar continues to load.  The previous version shows up as plugin to be activated but the newer one does not. 
![Untitled](https://user-images.githubusercontent.com/84614100/119295401-323ab780-bc70-11eb-96a5-0ec39f357b43.png)

**Comment by Vitaliy-1** [comment]
Did you install the [release package](https://github.com/Vitaliy-1/docxConverter/releases/tag/1.1.0) or through Git?

**Comment by waqas1223** [comment]
download zip file from git and extract in cpannel metadata
![Uploading Screenshot_1.jpg…]()

**Comment by Vitaliy-1** [comment]
@waqas1223, this won't work as the plugin has dependencies that should be installed. There are 2 ways of installation, download the packed release, they are listed here: https://github.com/Vitaliy-1/docxConverter/releases. Looks for the one that corresponds to your release. The package has `tar.gz` extension. e.g. here: https://github.com/Vitaliy-1/docxConverter/releases/tag/1.1.0, the first file `docxConverter-1.1.0.tar.gz`. It can be downloaded as all other plugins.

The second way is more advanced and involves installing Git and Composer first, then cloning the repository into the `plugins/generic` folder: `git clone --recurse-submodules https://github.com/Vitaliy-1/docxConverter.git`. Checkout one of the stable branches `cd docxConverter` , `git checkout stable-3_2_1`. And finally, install dependencies from the `docxToJats` dir with `composer install`

**Comment by waqas1223** [comment]
Dear Vitaliy-1: Thank you for the response. We are currently using OJS 3.2.1.0 for our journal www.archivessr.com which uses Default Theme, and considering the 3.2 version, have used the DOCX Converter 1.1.0 for it but it does not work for us. We downloaded the plugin from the site that you suggested. Would you like to advise us on it? or there is another way to you can personally install the plugin in our journals

**Comment by waqas1223** [comment]
and sir can you tell me directory path where is extract the file?
docxConverter in meta data?
texture in generic?
JATSParserPlugin in genreric?

**Comment by Vitaliy-1** [comment]
> docxConverter in meta data?

It should be in `generic` folder

> Dear Vitaliy-1: Thank you for the response. We are currently using OJS 3.2.1.0 for our journal www.archivessr.com which uses Default Theme, and considering the 3.2 version, have used the DOCX Converter 1.1.0 for it but it does not work for us

The plugin v.1.1.0 should work with OJS 3.2.1, I use it on our university's OJS production instance (it's also 3.2.1 version). Are there any errors in PHP log? What problems do you encounter after plugin installation? Does the button under DOCX file appear?

**Comment by waqas1223** [comment]
i install this plugin according to OJS 3.2.1.0 version in a gerneric folder. thier is no php log error but still cant get button under DOCX file appear. screen shot is attached.

[27-May-2021 03:39:01 UTC] PHP Deprecated:  Non-static method PKPApplication::getRequest() should not be called statically in /home/upcpmzqf/public_html/plugins/generic/customHeader/CustomHeaderPlugin.inc.php on line 112
[27-May-2021 03:40:31 UTC] PHP Deprecated:  Non-static method PKPApplication::getRequest() should not be called statically in /home/upcpmzqf/public_html/plugins/generic/customHeader/CustomHeaderPlugin.inc.php on line 112
[27-May-2021 03:41:01 UTC] PHP Deprecated:  Non-static method PKPApplication::getRequest() should not be called statically in /home/upcpmzqf/public_html/plugins/generic/customHeader/CustomHeaderPlugin.inc.php on line 112
[27-May-2021 03:41:08 UTC] PHP Deprecated:  Non-static method PKPApplication::getRequest() should not be called statically in /home/upcpmzqf/public_html/plugins/generic/customHeader/CustomHeaderPlugin.inc.php on line 112
![2](https://user-images.githubusercontent.com/84614100/119762873-ef731c80-bec7-11eb-9c74-fe3cf99954a2.jpg)
![1](https://user-images.githubusercontent.com/84614100/119762876-f13ce000-bec7-11eb-9dd8-d7b3fa1bf992.jpg)

**Comment by Vitaliy-1** [comment]
The file on the screenshot has `xml` extension and not `docx`. DOCX Converter Plugin is aimed to convert document files generated in text editors and exported in [Office Open XML format](https://en.wikipedia.org/wiki/Office_Open_XML) with `docx` extension (word processing documents).

**Comment by waqas1223** [comment]
oh thanks got it.now button is shown under the docs file. what about next do we need texture and jatparser plugin.

**Comment by Vitaliy-1** [comment]
Gald that you made it work. After conversion, the file can be edited with the Texture plugin if it's installed. The button should appear in the same way as with the DOCX Converter plugin but under JATS XML file.
I'm closing the issue as it's resolved.
