### ISSUE TITLE
Undefined array key "submission"

### ISSUE THREAD

**Issue by Rhynden** [Vitaliy-1/docxConverter#14]
Hello, 
with the latest version from https://github.com/pkp/ojs I get the following error:
`PHP Warning:  Undefined array key "submission" in C:\Users\flori\Documents\ojs\lib\pkp\lib\vendor\pimple\pimple\src\Pimple\Container.php on line 111
[Mon Dec 13 23:26:57 2021] PHP Warning:  Undefined array key "submission" in C:\Users\flori\Documents\ojs\lib\pkp\lib\vendor\pimple\pimple\src\Pimple\Container.php on line 115
[Mon Dec 13 23:26:57 2021] PHP Fatal error:  Uncaught Error: Call to a member function get() on null in C:\Users\flori\Documents\ojs\plugins\generic\docxConverter\DocxToJatsPlugin.inc.php:96
Stack trace:
#0 [internal function]: DocxToJatsPlugin->templateFetchCallback('TemplateManager...', Array)
#1 C:\Users\flori\Documents\ojs\lib\pkp\classes\plugins\HookRegistry.inc.php(122): call_user_func(Array, 'TemplateManager...', Array)
#2 C:\Users\flori\Documents\ojs\lib\pkp\classes\template\PKPTemplateManager.inc.php(1123): PKP\plugins\HookRegistry::call('TemplateManager...', Array)
#3 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\GridHandler.inc.php(1173): PKP\template\PKPTemplateManager->fetch('controllers/gri...')
#4 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(379): PKP\controllers\grid\GridHandler->renderRowInternally(Object(APP\core\Request), Object(SubmissionFilesGridRow))
#5 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\GridHandler.inc.php(1137): PKP\controllers\grid\CategoryGridHandler->renderRowInternally(Object(APP\core\Request), Object(SubmissionFilesGridRow))
#6 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(551): PKP\controllers\grid\GridHandler->renderRowsInternally(Object(APP\core\Request), Array)
#7 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(519): PKP\controllers\grid\CategoryGridHandler->_renderCategoryInternally(Object(APP\core\Request), Object(SelectableSubmissionFileListCategoryGridRow))
#8 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(321): PKP\controllers\grid\CategoryGridHandler->_renderCategoriesInternally(Object(APP\core\Request))
#9 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\GridHandler.inc.php(733): PKP\controllers\grid\CategoryGridHandler->doSpecificFetchGridActions(Array, Object(APP\core\Request), Object(APP\template\TemplateManager))
#10 [internal function]: PKP\controllers\grid\GridHandler->fetchGrid(Array, Object(APP\core\Request))
#11 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\PKPRouter.inc.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#12 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\PKPComponentRouter.inc.php(280): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#13 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\Dispatcher.inc.php(166): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#14 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\PKPApplication.inc.php(339): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#15 C:\Users\flori\Documents\ojs\index.php(68): PKP\core\PKPApplication->execute()
#16 {main}
  thrown in C:\Users\flori\Documents\ojs\plugins\generic\docxConverter\DocxToJatsPlugin.inc.php on line 96
[Mon Dec 13 23:26:57 2021] [::1]:53132 [500]: GET /index.php/wordtest/$$$call$$$/grid/files/final/manage-final-draft-files-grid/fetch-grid?submissionId=1&stageId=4&fileStage=6&_=1639434382907 - Uncaught Error: Call to a member function get() on null in C:\Users\flori\Documents\ojs\plugins\generic\docxConverter\DocxToJatsPlugin.inc.php:96
Stack trace:
#0 [internal function]: DocxToJatsPlugin->templateFetchCallback('TemplateManager...', Array)
#1 C:\Users\flori\Documents\ojs\lib\pkp\classes\plugins\HookRegistry.inc.php(122): call_user_func(Array, 'TemplateManager...', Array)
#2 C:\Users\flori\Documents\ojs\lib\pkp\classes\template\PKPTemplateManager.inc.php(1123): PKP\plugins\HookRegistry::call('TemplateManager...', Array)
#3 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\GridHandler.inc.php(1173): PKP\template\PKPTemplateManager->fetch('controllers/gri...')
#4 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(379): PKP\controllers\grid\GridHandler->renderRowInternally(Object(APP\core\Request), Object(SubmissionFilesGridRow))
#5 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\GridHandler.inc.php(1137): PKP\controllers\grid\CategoryGridHandler->renderRowInternally(Object(APP\core\Request), Object(SubmissionFilesGridRow))
#6 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(551): PKP\controllers\grid\GridHandler->renderRowsInternally(Object(APP\core\Request), Array)
#7 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(519): PKP\controllers\grid\CategoryGridHandler->_renderCategoryInternally(Object(APP\core\Request), Object(SelectableSubmissionFileListCategoryGridRow))
#8 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\CategoryGridHandler.inc.php(321): PKP\controllers\grid\CategoryGridHandler->_renderCategoriesInternally(Object(APP\core\Request))
#9 C:\Users\flori\Documents\ojs\lib\pkp\classes\controllers\grid\GridHandler.inc.php(733): PKP\controllers\grid\CategoryGridHandler->doSpecificFetchGridActions(Array, Object(APP\core\Request), Object(APP\template\TemplateManager))
#10 [internal function]: PKP\controllers\grid\GridHandler->fetchGrid(Array, Object(APP\core\Request))
#11 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\PKPRouter.inc.php(465): call_user_func(Array, Array, Object(APP\core\Request))
#12 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\PKPComponentRouter.inc.php(280): PKP\core\PKPRouter->_authorizeInitializeAndCallRequest(Array, Object(APP\core\Request), Array)
#13 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\Dispatcher.inc.php(166): PKP\core\PKPComponentRouter->route(Object(APP\core\Request))
#14 C:\Users\flori\Documents\ojs\lib\pkp\classes\core\PKPApplication.inc.php(339): PKP\core\Dispatcher->dispatch(Object(APP\core\Request))
#15 C:\Users\flori\Documents\ojs\index.php(68): PKP\core\PKPApplication->execute()
#16 {main}
  thrown in C:\Users\flori\Documents\ojs\plugins\generic\docxConverter\DocxToJatsPlugin.inc.php on line 96
`

Any idea/suggestions?
With what latest version has this been tested?

Cheers

**Comment by Vitaliy-1** [comment]
Hi @Rhynden,

What branch or version are you using? The main branch of the plugin is for development and may not work with OJS 3.3 or even the current OJS main branch

If you want to work with the latest changes, use `stable_3_3_0` branch https://github.com/Vitaliy-1/docxConverter/tree/stable-3_3_0 for OJS 3.3.0.8. Let me know if you are using compatible versions but the problem persists.

**Comment by Rhynden** [comment]
Hi @Vitaliy-1 ,
thanks for the quick reply.
I wasn't using any branch, but the latest release (DOCX Converter 1.1.1).
I will try the DOCX Converter 1.1.1 with the stable 3.3.0 version of ojs https://github.com/pkp/ojs/tree/stable-3_3_0 and see if it's working. I was using their main branch before.
The release DOCX converter 1.1.1 corresponds to the stable_3_3_0 branch of the plugin I assume?
Thanks in advance!

**Comment by Vitaliy-1** [comment]
> I will try the DOCX Converter 1.1.1 with the stable 3.3.0 version of ojs https://github.com/pkp/ojs/tree/stable-3_3_0 

I suggest using stable-3_3_0 branch of the DOCX Converter plugin if you are working with git anyway. 

> I was using their main branch before.

Yes, in the main branch of OJS `Services`, like Submission Service, were removed in favour of the Repo pattern, which hasn't been yet reflected in the plugin's main branch and won't be changed in plugin's stable branches. This causes the error you posted.

**Comment by Rhynden** [comment]
Yes, I got it working with git and the stable releases. 
Thank you very much!
