### ISSUE TITLE
Error messages

### ISSUE THREAD

**Issue by Jirrka** [Vitaliy-1/docxConverter#7]
After installation of doxConverter I have error.log full of following messages:

"[Wed Aug 05 06:29:34.037130 2020] [php7:warn] [pid 1312] [client 46.229.168.131:45658] PHP Warning:  Declaration of DocxToJatsPlugin::register($category, $path) should be compatible with LazyLoadPlugin::register($category, $path, $mainContextId = NULL) in /var/www/html/plugins/generic/docxConverter/DocxToJatsPlugin.inc.php on line 0"

Converter itself works.

Nice day

Jirka

**Comment by Vitaliy-1** [comment]
Thanks, the referenced commit should fix it.
